# Generated by Django 6.0.1 on 2026-01-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='podcast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
