# Generated by Django 6.0.1 on 2026-01-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0002_alter_podcast_options_podcast_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_human_verified',
            field=models.BooleanField(default=False),
        ),
    ]
